### ISSUE TITLE
I cant buy items | 6.2.3

### ISSUE THREAD

**Issue by MeHaVr** [EconomyS/EconomyShop#15]
When I want to buy an item the purchase gui is not displayed and only gives an error message 

Error Message 

`
[18:30:52 ERROR]: Could not pass event InventoryClickEvent to EconomyShopGUI v6.2.3
java.lang.NullPointerException: Cannot invoke "org.json.simple.JSONObject.get(Object)" because "this.skullCache" is null
	at me.gypopo.economyshopgui.files.SkullCache.getSkull(SkullCache.java:44) ~[EconomyShopGUI-6.2.3.jar:?]
	at me.gypopo.economyshopgui.util.SkullUtil.setSkullTexture(SkullUtil.java:285) ~[EconomyShopGUI-6.2.3.jar:?]
	at me.gypopo.economyshopgui.objects.navbar.NavBarItem.getItem(NavBarItem.java:165) ~[EconomyShopGUI-6.2.3.jar:?]
	at me.gypopo.economyshopgui.objects.navbar.NavBar.addTransactionNavBar(NavBar.java:261) ~[EconomyShopGUI-6.2.3.jar:?]
	at me.gypopo.economyshopgui.objects.TransactionMenu.open(TransactionMenu.java:396) ~[EconomyShopGUI-6.2.3.jar:?]
	at me.gypopo.economyshopgui.events.MenuHandler.onMenuClick(MenuHandler.java:111) ~[EconomyShopGUI-6.2.3.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor807.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-290]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-290]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-290]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3108) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-290]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

Please Fix it and good bey have a nice day :)

**Comment by memesalot** [comment]
What was the fix? It's still happening in the latest version

**Comment by MeHaVr** [comment]
You must delete skull.js or how it called
